### ISSUE TITLE
Directory Exclusion pattterns not correctly supported when running on a windows platform

### ISSUE THREAD

**Issue by frankfal** [blackducksoftware/hub-teamcity#17]
The "Directory Exclusion Patterns" field is not correctly supported when running scan on a window platform. This same scan completed successfully on linux platform. You see an warning due to the pattern not starting with "/". In the case of windows, these patterns will start with a drive letter. The same issue probably exists in the "Scan Targets", but I didn't test it.

Error:

[Hub Build Step] Invalid Configuration: EXCLUDE_PATTERNS = WARN,The exclusion pattern : D:\TeamCity\buildAgent\work\6f2a6174975721fb/SXe/baselines/apogee/ must start with a /.
[12:31:48]
[Hub Build Step] java.lang.IllegalStateException: Invalid Configuration: EXCLUDE_PATTERNS = WARN,The exclusion pattern : D:\TeamCity\buildAgent\work\6f2a6174975721fb/SXe/baselines/apogee/ must start with a /. 
	at com.blackducksoftware.integration.builder.AbstractBuilder.build(AbstractBuilder.java:47)
	at com.blackducksoftware.integration.hub.teamcity.agent.scan.HubBuildProcess.getScanConfig(HubBuildProcess.java:376)
	at com.blackducksoftware.integration.hub.teamcity.agent.scan.HubBuildProcess.call(HubBuildProcess.java:203)
	at com.blackducksoftware.integration.hub.teamcity.agent.scan.HubBuildProcess.call(HubBuildProcess.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[12:31:48][Hub Build Step] Please verify the Black Duck Hub Runner configuration is correct.
[12:31:49][Hub Build Step] Step SXe (Black Duck Hub) failed

**Comment by frankfal** [comment]
Never mind, I found that these paths need to be relative to the work area.
